"""RotorHazard v2 event adapter; audio is generated by the service."""

from __future__ import annotations

import json
import math
import os
import time
import uuid
from pathlib import Path
from typing import Any

from eventmanager import Evt
from filtermanager import Flt
from gevent import monkey

from . import const
from .event_output import EventPublisher
from .services.clock_callouts import ClockCallouts
from .services.schedule import ScheduleCalloutManager
from .ui import register_ui

_LOCALES = json.loads((Path(__file__).parent / "locales.json").read_text())
_COMPETITION_OPTION = "race_voice_competition_id"
_OPTIONS = {
    const.ENABLE_OPTION,
    const.VOICE_MODEL_OPTION,
    const.SPEECH_SPEED_OPTION,
    const.NOISE_SCALE_OPTION,
    const.NOISE_W_SCALE_OPTION,
    const.SENDSPIN_SERVICE_URL_OPTION,
}


def _locale(model: str) -> dict:
    return _LOCALES.get(model[:2], _LOCALES["en"])


class RaceEventAdapter:
    """Capture RH values on callbacks and hand bounded copies to the publisher."""

    def __init__(self, rhapi: Any) -> None:
        """Capture race state without importing the old Piper plugin."""
        if not all(monkey.is_module_patched(name) for name in ("socket", "threading")):
            raise RuntimeError(
                "The event adapter requires RotorHazard's gevent-patched sockets"
            )
        self._rhapi = rhapi
        self._publisher = EventPublisher(
            token=os.environ.get("RACE_VOICE_SERVICE_TOKEN", "")
        )
        self._snapshot: dict | None = None
        self._competition = ""
        self._revision = self._generation = 0
        self._clock = ClockCallouts(locale_for_model=_locale)
        self._schedule = ScheduleCalloutManager(
            enqueue_callout=self._scheduled_phrase,
            phrase_for=lambda seconds, state: _locale(state["voice"]["model"])[
                "race_schedule"
            ].get(str(seconds), f"Race begins in {seconds} seconds"),
        )
        register_ui(
            rhapi,
            self.generate_test_phrase,
            self.audio_check,
            self.stop_audio,
            self.clear_cache,
            self.prepare_cache,
            event_mode=True,
        )
        for name, label, function in (
            ("race_voice_connect", "Connect / take over service", self.connect),
            ("race_voice_status", "Service status", self.show_status),
        ):
            rhapi.ui.register_quickbutton(
                panel=const.PANEL_ID, name=name, label=label, function=function
            )
        self._register()

    def _register(self) -> None:
        for event, callback in (
            (Evt.STARTUP, self._startup),
            (Evt.SHUTDOWN, self.close),
            (Evt.HEAT_SET, self._heat),
            (Evt.OPTION_SET, self._option_changed),
            (Evt.RACE_STAGE_TONE, self._stage),
            (Evt.RACE_START, self._race_start),
            (Evt.RACE_CLOCK_CALLOUT, self._clock_callout),
            (Evt.RACE_SCHEDULE, self._race_schedule),
            (Evt.RACE_SCHEDULE_CANCEL, self.stop_audio),
        ):
            self._rhapi.events.on(event, callback, name=f"race_voice_event_{event}")
        for event in (Evt.PILOT_ADD, Evt.PILOT_ALTER, Evt.HEAT_ALTER, Evt.HEAT_DELETE):
            self._rhapi.events.on(
                event, self._refresh, name=f"race_voice_event_{event}"
            )
        for event in (
            Evt.DATABASE_RESET,
            Evt.DATABASE_IMPORT,
            Evt.DATABASE_RESTORE,
            Evt.DATABASE_RECOVER,
            Evt.DATABASE_INITIALIZE,
            Evt.PILOT_DELETE,
        ):
            self._rhapi.events.on(event, self._reset, name=f"race_voice_event_{event}")
        self._rhapi.filters.add(
            Flt.EMIT_PHONETIC_DATA, "race_voice_phonetic_data", self._lap
        )
        self._rhapi.filters.add(
            Flt.EMIT_PHONETIC_TEXT, "race_voice_phonetic_text", self._voice
        )

    def _startup(self, _args: dict | None = None) -> None:
        self._refresh()
        self._publisher.start()

    def _option(self, name: str, default: Any) -> Any:
        value = self._rhapi.db.option(name, default=default)
        return default if value is False else value

    def _voice_settings(self) -> dict:
        model = self._option(const.VOICE_MODEL_OPTION, const.DEFAULT_MODEL)
        voice = {
            "model": model if model in const.VOICE_MODELS else const.DEFAULT_MODEL,
            "enabled": str(self._option(const.ENABLE_OPTION, default=False)).lower()
            not in {"false", "0", "no", ""},
            "callout_flags": {},
        }
        for key, option, default in (
            ("speed", const.SPEECH_SPEED_OPTION, const.DEFAULT_SPEED),
            ("noise", const.NOISE_SCALE_OPTION, const.DEFAULT_NOISE_SCALE),
            ("noise_w", const.NOISE_W_SCALE_OPTION, const.DEFAULT_NOISE_W_SCALE),
        ):
            try:
                value = float(self._option(option, default))
            except (TypeError, ValueError):
                value = float(default)
            voice[key] = (
                value
                if math.isfinite(value)
                and (0.1 if key == "speed" else 0) <= value <= 10
                else float(default)
            )
        return voice

    def _roster(self, heat_id: int | None) -> list[dict]:
        if heat_id is None:
            return []
        pilots = {}
        for slot in self._rhapi.db.slots_by_heat(heat_id):
            if not slot.pilot_id:
                continue
            pilot = self._rhapi.db.pilot_by_id(slot.pilot_id)
            if pilot is not None:
                pilots[pilot.id] = {
                    "pilot_id": pilot.id,
                    "callsign": str(pilot.callsign or pilot.id)[:128],
                    "spoken_name": str(pilot.phonetic or pilot.callsign or "")[:256],
                    "node": slot.node_index,
                }
        if len(pilots) > 256:
            raise ValueError("Too many pilots in the current heat")
        return list(pilots.values())

    def _refresh(self, _args: dict | None = None, *, invalidate: bool = False) -> None:
        if not self._competition:
            self._competition = (
                self._option(_COMPETITION_OPTION, "") or uuid.uuid4().hex
            )
            self._rhapi.db.option_set(_COMPETITION_OPTION, self._competition)
        heat_id = self._rhapi.race.heat or None
        heat = self._rhapi.db.heat_by_id(heat_id) if heat_id else None
        state = {
            "version": "race-events/1",
            "heat_name": str(heat.name or "")[:256] if heat else "",
            "pilots": self._roster(heat_id),
            "voice": self._voice_settings(),
        }
        old = self._snapshot
        sound_changed = old is not None and (
            old["voice"] != state["voice"]
            or old["context"]["heat_id"] != heat_id
            or old["context"]["competition_id"] != self._competition
        )
        if invalidate or sound_changed:
            self._generation += 1
            self._schedule.cancel()
        self._revision += 1
        state["context"] = {
            "competition_id": self._competition,
            "revision": self._revision,
            "generation": self._generation,
            "heat_id": heat_id,
        }
        self._snapshot = state
        url = str(
            self._option(
                const.SENDSPIN_SERVICE_URL_OPTION, const.DEFAULT_SENDSPIN_SERVICE_URL
            )
            or const.DEFAULT_SENDSPIN_SERVICE_URL
        ).strip()
        self._publisher.update(state, url)

    def _option_changed(self, args: dict) -> None:
        if args.get("option") in _OPTIONS:
            self._refresh()

    def _heat(self, _args: dict) -> None:
        self._refresh(invalidate=True)

    def _reset(self, _args: dict) -> None:
        self._competition = uuid.uuid4().hex
        self._rhapi.db.option_set(_COMPETITION_OPTION, self._competition)
        self._refresh(invalidate=True)

    def _emit(
        self, kind: str, payload: dict, *, ttl: float = 10, target: float | None = None
    ) -> bool:
        if self._snapshot is None or not self._snapshot["voice"]["enabled"]:
            return False
        text = payload.get("text")
        if kind != "tone" and (
            not isinstance(text, str) or not text.strip() or len(text) > 4096
        ):
            return False
        if len(payload.get("pilot_name", "")) > 256:
            return False
        if target is not None and (
            type(target) not in (int, float) or not math.isfinite(target)
        ):
            return False
        now = time.monotonic()
        return self._publisher.submit(
            kind,
            payload,
            expires_at=(target if target is not None else now) + ttl,
            play_at=target,
        )

    def _lap(self, payload: dict) -> dict:
        if payload.get("lap", 0) > 0:
            self._emit(
                "lap",
                {
                    "pilot_id": payload.get("pilot_id"),
                    "pilot_name": str(payload.get("pilot") or ""),
                    "lap": payload["lap"],
                    "text": str(payload.get("phonetic") or ""),
                },
            )
        return payload

    def _voice(self, payload: dict) -> dict:
        if isinstance(payload.get("text"), str) and payload["text"].strip():
            self._emit(
                "voice",
                {
                    "text": payload["text"],
                    "winner_flag": bool(payload.get("winner_flag")),
                },
                ttl=5,
            )
        return payload

    def _stage(self, args: dict) -> None:
        self._emit(
            "tone",
            {"asset": "stage"},
            ttl=0.25,
            target=args.get("scheduled_at_monotonic"),
        )

    def _race_start(self, _args: dict) -> None:
        self._emit(
            "tone",
            {"asset": "buzzer"},
            ttl=1,
            target=self._rhapi.race.start_time_internal,
        )

    def _clock_callout(self, args: dict) -> None:
        plan = self._clock.plan(args.get("seconds_remaining"))
        if plan is None or self._snapshot is None:
            return
        target = args.get("scheduled_at_monotonic")
        if plan.kind in {"tone", "buzzer"}:
            self._emit(
                "tone",
                {"asset": "stage" if plan.kind == "tone" else "buzzer"},
                ttl=0.25 if plan.kind == "tone" else 1,
                target=target,
            )
        else:
            text = self._clock.phrase(plan.seconds, self._snapshot["voice"]["model"])
            self._emit("countdown", {"text": text}, ttl=8, target=target)

    def _race_schedule(self, args: dict) -> None:
        if (
            self._snapshot is not None
            and self._snapshot["voice"]["enabled"]
            and args.get("scheduled_at") is not None
        ):
            self._schedule.schedule(args["scheduled_at"], self._snapshot)

    def _scheduled_phrase(self, text: str, state: dict) -> None:
        if (
            self._snapshot is not None
            and state["context"]["generation"] == self._generation
        ):
            self._emit("countdown", {"text": text}, ttl=8)

    def stop_audio(self, _args: dict | None = None) -> None:
        """Cancel local pending work and publish a new stop generation."""
        self._refresh(invalidate=True)

    def generate_test_phrase(self, _args: dict | None = None) -> None:
        """Send the operator's test text through the same service event path."""
        self._report_test(
            self._emit(
                "voice",
                {
                    "text": str(
                        self._option(
                            const.TEST_PHRASE_OPTION, const.DEFAULT_TEST_PHRASE
                        )
                    ),
                    "winner_flag": True,
                },
            )
        )

    def audio_check(self, _args: dict | None = None) -> None:
        """Request the service's bundled audio-check asset without opening a WAV."""
        self._report_test(self._emit("tone", {"asset": "audio_check"}, ttl=45))

    def _report_test(self, queued: bool) -> None:  # noqa: FBT001
        message = (
            "Audio test queued"
            if queued
            else "Enable plugin audio and check service status before testing"
        )
        self._rhapi.ui.message_notify(message)

    def connect(self, _args: dict | None = None) -> None:
        """Explicitly allow this RH process to replace a previous publisher."""
        self._refresh(invalidate=True)
        self._publisher.take_over()
        self._publisher.start()
        self._rhapi.ui.message_notify(
            "Connection requested; use Service status to check the result"
        )

    def show_status(self, _args: dict | None = None) -> None:
        """Read publisher status on the RH side, without performing a request."""
        self._rhapi.ui.message_notify(
            f"Race Voice: {self._publisher.status}; {self._publisher.command_status}"
        )

    def prepare_cache(self, _args: dict | None = None) -> None:
        """Prepare the captured heat roster and reusable phrases in the service."""
        self._cache_command("prepare")

    def clear_cache(self, _args: dict | None = None) -> None:
        """Fence old callouts before asking the service to clear the voice cache."""
        self._cache_command("clear_cache")

    def _cache_command(self, operation: str) -> None:
        if not self._publisher.can_command():
            self._rhapi.ui.message_alert(
                "Check service status: disconnected or a cache command is still running"
            )
            return
        if operation == "clear_cache":
            self.stop_audio()
        self._publisher.command(operation)
        self._rhapi.ui.message_notify(
            "Cache command queued; use Service status to check progress"
        )

    def close(self, _args: dict | None = None) -> None:
        """Discard timers and transport work on RH shutdown."""
        self._schedule.cancel()
        self._publisher.close()
