"""UI panel, options, and quick-buttons registration for Race Voice."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from flask import Blueprint, send_from_directory
from RHUI import UIField, UIFieldSelectOption, UIFieldType

from .const import (
    DEFAULT_MODEL,
    DEFAULT_NOISE_SCALE,
    DEFAULT_NOISE_W_SCALE,
    DEFAULT_SENDSPIN_SERVICE_TIMEOUT,
    DEFAULT_SENDSPIN_SERVICE_URL,
    DEFAULT_SPEED,
    DEFAULT_TEST_PHRASE,
    ENABLE_OPTION,
    NOISE_SCALE_OPTION,
    NOISE_W_SCALE_OPTION,
    PANEL_ID,
    SENDSPIN_SERVICE_TIMEOUT_OPTION,
    SENDSPIN_SERVICE_URL_OPTION,
    SPEECH_SPEED_OPTION,
    TEST_PHRASE_OPTION,
    VOICE_MODEL_OPTION,
    VOICE_MODELS,
)

_PLAYER_DIR = Path(__file__).parent / "player"


def register_ui(  # noqa: PLR0913
    rhapi: Any,
    test_callback: Any,
    audio_check_callback: Any,
    stop_audio_callback: Any,
    clear_cache_callback: Any,
    rebuild_precache_callback: Any,
) -> None:
    """Register the Race Voice settings panel, options, and quick buttons."""
    _register_player_blueprint(rhapi)
    rhapi.ui.register_panel(PANEL_ID, "Race Voice", "run", open=False)

    rhapi.fields.register_option(
        UIField(
            ENABLE_OPTION,
            "Enable plugin audio",
            UIFieldType.CHECKBOX,
            value=False,
            desc="Generate server-side race voice callout WAV files.",
        ),
        panel=PANEL_ID,
    )
    rhapi.fields.register_option(
        UIField(
            SENDSPIN_SERVICE_URL_OPTION,
            "Sendspin service URL",
            UIFieldType.TEXT,
            value=DEFAULT_SENDSPIN_SERVICE_URL,
            desc="Local HTTP endpoint for sendspin-service.",
        ),
        panel=PANEL_ID,
    )
    rhapi.fields.register_option(
        UIField(
            SENDSPIN_SERVICE_TIMEOUT_OPTION,
            "Sendspin service timeout",
            UIFieldType.NUMBER,
            value=DEFAULT_SENDSPIN_SERVICE_TIMEOUT,
            desc="HTTP timeout in seconds for service requests.",
            html_attributes={"min": "0.2", "max": "10.0", "step": "0.1"},
        ),
        panel=PANEL_ID,
    )
    rhapi.fields.register_option(
        UIField(
            VOICE_MODEL_OPTION,
            "Voice model",
            UIFieldType.SELECT,
            value=DEFAULT_MODEL,
            options=[
                UIFieldSelectOption(model_name, model["label"])
                for model_name, model in VOICE_MODELS.items()
            ],
            desc="Downloaded once into the local RotorHazard data cache.",
        ),
        panel=PANEL_ID,
    )
    rhapi.fields.register_option(
        UIField(
            SPEECH_SPEED_OPTION,
            "Speech speed",
            UIFieldType.NUMBER,
            value=DEFAULT_SPEED,
            desc="Speech rate (0.5 = slow, 1.0 = Piper default, 2.0 = fast).",
            html_attributes={"min": "0.5", "max": "2.0", "step": "0.05"},
        ),
        panel=PANEL_ID,
    )
    rhapi.fields.register_option(
        UIField(
            NOISE_SCALE_OPTION,
            "Noise scale",
            UIFieldType.NUMBER,
            value=DEFAULT_NOISE_SCALE,
            desc="Generator noise (0.0 = monotone, 1.0 = expressive). Default: 0.667.",
            html_attributes={"min": "0.0", "max": "2.0", "step": "0.05"},
        ),
        panel=PANEL_ID,
    )
    rhapi.fields.register_option(
        UIField(
            NOISE_W_SCALE_OPTION,
            "Phoneme width noise",
            UIFieldType.NUMBER,
            value=DEFAULT_NOISE_W_SCALE,
            desc="Phoneme duration noise (0.0 = uniform, 1.0 = varied). Default: 0.8.",
            html_attributes={"min": "0.0", "max": "2.0", "step": "0.05"},
        ),
        panel=PANEL_ID,
    )

    # Panel notes
    rhapi.ui.register_markdown(
        PANEL_ID,
        "race_voice_notes",
        '<a href="/player" target="_blank" rel="noopener noreferrer">'
        "Open browser player in a new tab</a>\n\n"
        "⚠ Set Voice Volume and Tone Volume to 0 on all browser clients.\n\n"
        "After first setup or voice model/settings changes, use Rebuild pre-cache to "
        "prepare schedule and current-heat WAV files.",
    )

    # Test phrase
    rhapi.fields.register_option(
        UIField(
            TEST_PHRASE_OPTION,
            "Test phrase",
            UIFieldType.TEXT,
            value=DEFAULT_TEST_PHRASE,
            placeholder=DEFAULT_TEST_PHRASE,
            desc="Phrase generated by the test button.",
        ),
        panel=PANEL_ID,
    )
    rhapi.ui.register_quickbutton(
        panel=PANEL_ID,
        name="race_voice_test_phrase",
        label="Generate test phrase",
        function=test_callback,
    )
    rhapi.ui.register_quickbutton(
        panel=PANEL_ID,
        name="race_voice_audio_check",
        label="Play audio check",
        function=audio_check_callback,
    )
    rhapi.ui.register_quickbutton(
        panel=PANEL_ID,
        name="race_voice_stop_audio",
        label="Stop audio",
        function=stop_audio_callback,
    )
    rhapi.ui.register_quickbutton(
        panel=PANEL_ID,
        name="race_voice_clear_cache",
        label="Clear TTS cache",
        function=clear_cache_callback,
    )
    rhapi.ui.register_quickbutton(
        panel=PANEL_ID,
        name="race_voice_rebuild_precache",
        label="Rebuild pre-cache",
        function=rebuild_precache_callback,
    )


def _register_player_blueprint(rhapi: Any) -> None:
    """Serve the Sendspin browser player at /player."""
    bp = Blueprint("race_voice_player", __name__)

    @bp.route("/player")
    def player_page() -> Any:
        return send_from_directory(str(_PLAYER_DIR), "index.html")

    @bp.route("/player/<path:filename>")
    def player_asset(filename: str) -> Any:
        return send_from_directory(str(_PLAYER_DIR), filename)

    rhapi.ui.blueprint_add(bp)
