---
name: Build
on:
  pull_request:
    paths:
      - .github/actions/build-sendspin-deb/**
      - .github/actions/build-sendspin-docker/**
      - .github/workflows/build.yaml
      - .github/workflows/release.yaml
      - .dockerignore
      - Dockerfile
      - sendspin_player/**
      - sendspin_service/**
      - tools/build_sendspin_service_deb.py
      - packaging/**
      - pyproject.toml
      - uv.lock

permissions:
  contents: read

jobs:
  build-deb:
    name: Sendspin service .deb
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
      - name: 🏗 Build .deb
        uses: ./.github/actions/build-sendspin-deb
        with:
          arch: amd64

  build-docker:
    name: Sendspin service Docker
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.1
      - name: 🏗 Build Docker image
        uses: ./.github/actions/build-sendspin-docker
        with:
          service-version: 0.0.0+dev
